<?php

use Carbon\Carbon;
use App\Models\Location\City;
use Illuminate\Database\Seeder;
use App\Models\Location\Country;
use App\Models\Location\Province;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::select('SET FOREIGN_KEY_CHECKS=0;');
        Country::truncate();
        Province::truncate();
        City::truncate();
        DB::select('SET FOREIGN_KEY_CHECKS=1;');

        Country::insert([
            ['id' => '1', 'name' => 'Indonesia', 'created_at' => now(), 'updated_at' => now()]
        ]);

        Province::insert([
            ['id' => '11', 'name' => 'Aceh', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '12', 'name' => 'Sumatera Utara', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '13', 'name' => 'Sumatera Barat', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '14', 'name' => 'Riau', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '15', 'name' => 'Jambi', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '16', 'name' => 'Sumatera Selatan', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '17', 'name' => 'Bengkulu', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '18', 'name' => 'Lampung', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '19', 'name' => 'Kepulauan Bangka Belitung', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '21', 'name' => 'Kepulauan Riau', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '31', 'name' => 'Dki Jakarta', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '32', 'name' => 'Jawa Barat', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '33', 'name' => 'Jawa Tengah', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '34', 'name' => 'Di Yogyakarta', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '35', 'name' => 'Jawa Timur', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '36', 'name' => 'Banten', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '51', 'name' => 'Bali', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '52', 'name' => 'Nusa Tenggara Barat', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '53', 'name' => 'Nusa Tenggara Timur', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '61', 'name' => 'Kalimantan Barat', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '62', 'name' => 'Kalimantan Tengah', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '63', 'name' => 'Kalimantan Selatan', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '64', 'name' => 'Kalimantan Timur', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '65', 'name' => 'Kalimantan Utara', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '71', 'name' => 'Sulawesi Utara', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '72', 'name' => 'Sulawesi Tengah', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '73', 'name' => 'Sulawesi Selatan', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '74', 'name' => 'Sulawesi Tenggara', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '75', 'name' => 'Gorontalo', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '76', 'name' => 'Sulawesi Barat', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '81', 'name' => 'Maluku', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '82', 'name' => 'Maluku Utara', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '91', 'name' => 'Papua Barat', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '94', 'name' => 'Papua', 'country_id' => '1', 'created_at' => now(), 'updated_at' => now()]
        ]);

        City::insert([
            ['id' => '1101', 'province_id' => 11, 'name' => 'Simeulue', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1102', 'province_id' => 11, 'name' => 'Aceh Singkil', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1103', 'province_id' => 11, 'name' => 'Aceh Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1104', 'province_id' => 11, 'name' => 'Aceh Tenggara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1105', 'province_id' => 11, 'name' => 'Aceh Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1106', 'province_id' => 11, 'name' => 'Aceh Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1107', 'province_id' => 11, 'name' => 'Aceh Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1108', 'province_id' => 11, 'name' => 'Aceh Besar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1109', 'province_id' => 11, 'name' => 'Pidie', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1110', 'province_id' => 11, 'name' => 'Bireuen', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1111', 'province_id' => 11, 'name' => 'Aceh Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1112', 'province_id' => 11, 'name' => 'Aceh Barat Daya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1113', 'province_id' => 11, 'name' => 'Gayo Lues', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1114', 'province_id' => 11, 'name' => 'Aceh Tamiang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1115', 'province_id' => 11, 'name' => 'Nagan Raya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1116', 'province_id' => 11, 'name' => 'Aceh Jaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1117', 'province_id' => 11, 'name' => 'Bener Meriah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1118', 'province_id' => 11, 'name' => 'Pidie Jaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1171', 'province_id' => 11, 'name' => 'Banda Aceh', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1172', 'province_id' => 11, 'name' => 'Sabang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1173', 'province_id' => 11, 'name' => 'Langsa', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1174', 'province_id' => 11, 'name' => 'Lhokseumawe', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1175', 'province_id' => 11, 'name' => 'Subulussalam', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1201', 'province_id' => 12, 'name' => 'Nias', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1202', 'province_id' => 12, 'name' => 'Mandailing Natal', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1203', 'province_id' => 12, 'name' => 'Tapanuli Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1204', 'province_id' => 12, 'name' => 'Tapanuli Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1205', 'province_id' => 12, 'name' => 'Tapanuli Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1206', 'province_id' => 12, 'name' => 'Toba Samosir', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1207', 'province_id' => 12, 'name' => 'Labuhan Batu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1208', 'province_id' => 12, 'name' => 'Asahan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1209', 'province_id' => 12, 'name' => 'Simalungun', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1210', 'province_id' => 12, 'name' => 'Dairi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1211', 'province_id' => 12, 'name' => 'Karo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1212', 'province_id' => 12, 'name' => 'Deli Serdang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1213', 'province_id' => 12, 'name' => 'Langkat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1214', 'province_id' => 12, 'name' => 'Nias Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1215', 'province_id' => 12, 'name' => 'Humbang Hasundutan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1216', 'province_id' => 12, 'name' => 'Pakpak Bharat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1217', 'province_id' => 12, 'name' => 'Samosir', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1218', 'province_id' => 12, 'name' => 'Serdang Bedagai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1219', 'province_id' => 12, 'name' => 'Batu Bara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1220', 'province_id' => 12, 'name' => 'Padang Lawas Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1221', 'province_id' => 12, 'name' => 'Padang Lawas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1222', 'province_id' => 12, 'name' => 'Labuhan Batu Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1223', 'province_id' => 12, 'name' => 'Labuhan Batu Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1224', 'province_id' => 12, 'name' => 'Nias Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1225', 'province_id' => 12, 'name' => 'Nias Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1271', 'province_id' => 12, 'name' => 'Sibolga', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1272', 'province_id' => 12, 'name' => 'Tanjung Balai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1273', 'province_id' => 12, 'name' => 'Pematang Siantar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1274', 'province_id' => 12, 'name' => 'Tebing Tinggi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1275', 'province_id' => 12, 'name' => 'Medan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1276', 'province_id' => 12, 'name' => 'Binjai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1277', 'province_id' => 12, 'name' => 'Padang Sidempuan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1278', 'province_id' => 12, 'name' => 'Gunungsitoli', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1301', 'province_id' => 13, 'name' => 'Kepulauan Mentawai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1302', 'province_id' => 13, 'name' => 'Pesisir Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1303', 'province_id' => 13, 'name' => 'Solok', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1304', 'province_id' => 13, 'name' => 'Sijunjung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1305', 'province_id' => 13, 'name' => 'Tanah Datar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1306', 'province_id' => 13, 'name' => 'Padang Pariaman', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1307', 'province_id' => 13, 'name' => 'Agam', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1308', 'province_id' => 13, 'name' => 'Lima Puluh Kota', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1309', 'province_id' => 13, 'name' => 'Pasaman', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1310', 'province_id' => 13, 'name' => 'Solok Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1311', 'province_id' => 13, 'name' => 'Dharmasraya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1312', 'province_id' => 13, 'name' => 'Pasaman Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1371', 'province_id' => 13, 'name' => 'Padang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1373', 'province_id' => 13, 'name' => 'Sawah Lunto', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1374', 'province_id' => 13, 'name' => 'Padang Panjang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1375', 'province_id' => 13, 'name' => 'Bukittinggi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1376', 'province_id' => 13, 'name' => 'Payakumbuh', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1377', 'province_id' => 13, 'name' => 'Pariaman', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1401', 'province_id' => 14, 'name' => 'Kuantan Singingi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1402', 'province_id' => 14, 'name' => 'Indragiri Hulu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1403', 'province_id' => 14, 'name' => 'Indragiri Hilir', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1404', 'province_id' => 14, 'name' => 'Pelalawan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1405', 'province_id' => 14, 'name' => 'Siak', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1406', 'province_id' => 14, 'name' => 'Kampar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1407', 'province_id' => 14, 'name' => 'Rokan Hulu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1408', 'province_id' => 14, 'name' => 'Bengkalis', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1409', 'province_id' => 14, 'name' => 'Rokan Hilir', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1410', 'province_id' => 14, 'name' => 'Kepulauan Meranti', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1471', 'province_id' => 14, 'name' => 'Pekanbaru', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1473', 'province_id' => 14, 'name' => 'Dumai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1501', 'province_id' => 15, 'name' => 'Kerinci', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1502', 'province_id' => 15, 'name' => 'Merangin', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1503', 'province_id' => 15, 'name' => 'Sarolangun', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1504', 'province_id' => 15, 'name' => 'Batang Hari', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1505', 'province_id' => 15, 'name' => 'Muaro Jambi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1506', 'province_id' => 15, 'name' => 'Tanjung Jabung Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1507', 'province_id' => 15, 'name' => 'Tanjung Jabung Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1508', 'province_id' => 15, 'name' => 'Tebo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1509', 'province_id' => 15, 'name' => 'Bungo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1571', 'province_id' => 15, 'name' => 'Jambi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1572', 'province_id' => 15, 'name' => 'Sungai Penuh', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1601', 'province_id' => 16, 'name' => 'Ogan Komering Ulu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1602', 'province_id' => 16, 'name' => 'Ogan Komering Ilir', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1603', 'province_id' => 16, 'name' => 'Muara Enim', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1604', 'province_id' => 16, 'name' => 'Lahat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1605', 'province_id' => 16, 'name' => 'Musi Rawas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1606', 'province_id' => 16, 'name' => 'Musi Banyuasin', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1607', 'province_id' => 16, 'name' => 'Banyu Asin', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1608', 'province_id' => 16, 'name' => 'Ogan Komering Ulu Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1609', 'province_id' => 16, 'name' => 'Ogan Komering Ulu Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1610', 'province_id' => 16, 'name' => 'Ogan Ilir', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1611', 'province_id' => 16, 'name' => 'Empat Lawang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1612', 'province_id' => 16, 'name' => 'Penukal Abab Lematang Ilir', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1613', 'province_id' => 16, 'name' => 'Musi Rawas Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1671', 'province_id' => 16, 'name' => 'Palembang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1672', 'province_id' => 16, 'name' => 'Prabumulih', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1673', 'province_id' => 16, 'name' => 'Pagar Alam', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1674', 'province_id' => 16, 'name' => 'Lubuk Linggau', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1701', 'province_id' => 17, 'name' => 'Bengkulu Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1702', 'province_id' => 17, 'name' => 'Rejang Lebong', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1703', 'province_id' => 17, 'name' => 'Bengkulu Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1704', 'province_id' => 17, 'name' => 'Kaur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1705', 'province_id' => 17, 'name' => 'Seluma', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1706', 'province_id' => 17, 'name' => 'Muko Muko', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1707', 'province_id' => 17, 'name' => 'Lebong', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1708', 'province_id' => 17, 'name' => 'Kepahiang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1709', 'province_id' => 17, 'name' => 'Bengkulu Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1771', 'province_id' => 17, 'name' => 'Bengkulu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1801', 'province_id' => 18, 'name' => 'Lampung Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1802', 'province_id' => 18, 'name' => 'Tanggamus', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1803', 'province_id' => 18, 'name' => 'Lampung Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1804', 'province_id' => 18, 'name' => 'Lampung Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1805', 'province_id' => 18, 'name' => 'Lampung Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1806', 'province_id' => 18, 'name' => 'Lampung Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1807', 'province_id' => 18, 'name' => 'Way Kanan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1808', 'province_id' => 18, 'name' => 'Tulang Bawang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1809', 'province_id' => 18, 'name' => 'Pesawaran', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1810', 'province_id' => 18, 'name' => 'Pringsewu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1811', 'province_id' => 18, 'name' => 'Mesuji', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1812', 'province_id' => 18, 'name' => 'Tulang Bawang Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1813', 'province_id' => 18, 'name' => 'Pesisir Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1871', 'province_id' => 18, 'name' => 'Bandar Lampung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1872', 'province_id' => 18, 'name' => 'Metro', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1901', 'province_id' => 19, 'name' => 'Bangka', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1902', 'province_id' => 19, 'name' => 'Belitung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1903', 'province_id' => 19, 'name' => 'Bangka Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1904', 'province_id' => 19, 'name' => 'Bangka Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1905', 'province_id' => 19, 'name' => 'Bangka Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1906', 'province_id' => 19, 'name' => 'Belitung Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '1971', 'province_id' => 19, 'name' => 'Pangkal Pinang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '2101', 'province_id' => 21, 'name' => 'Karimun', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '2102', 'province_id' => 21, 'name' => 'Bintan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '2103', 'province_id' => 21, 'name' => 'Natuna', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '2104', 'province_id' => 21, 'name' => 'Lingga', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '2105', 'province_id' => 21, 'name' => 'Kepulauan Anambas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '2171', 'province_id' => 21, 'name' => 'Batam', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '2172', 'province_id' => 21, 'name' => 'Tanjung Pinang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3101', 'province_id' => 31, 'name' => 'Kepulauan Seribu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3171', 'province_id' => 31, 'name' => 'Jakarta Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3172', 'province_id' => 31, 'name' => 'Jakarta Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3173', 'province_id' => 31, 'name' => 'Jakarta Pusat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3174', 'province_id' => 31, 'name' => 'Jakarta Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3175', 'province_id' => 31, 'name' => 'Jakarta Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3203', 'province_id' => 32, 'name' => 'Cianjur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3204', 'province_id' => 32, 'name' => 'Bandung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3205', 'province_id' => 32, 'name' => 'Garut', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3206', 'province_id' => 32, 'name' => 'Tasikmalaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3207', 'province_id' => 32, 'name' => 'Ciamis', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3208', 'province_id' => 32, 'name' => 'Kuningan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3210', 'province_id' => 32, 'name' => 'Majalengka', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3211', 'province_id' => 32, 'name' => 'Sumedang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3212', 'province_id' => 32, 'name' => 'Indramayu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3213', 'province_id' => 32, 'name' => 'Subang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3214', 'province_id' => 32, 'name' => 'Purwakarta', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3215', 'province_id' => 32, 'name' => 'Karawang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3216', 'province_id' => 32, 'name' => 'Bekasi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3217', 'province_id' => 32, 'name' => 'Bandung Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3218', 'province_id' => 32, 'name' => 'Pangandaran', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3271', 'province_id' => 32, 'name' => 'Bogor', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3272', 'province_id' => 32, 'name' => 'Sukabumi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3274', 'province_id' => 32, 'name' => 'Cirebon', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3276', 'province_id' => 32, 'name' => 'Depok', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3277', 'province_id' => 32, 'name' => 'Cimahi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3279', 'province_id' => 32, 'name' => 'Banjar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3301', 'province_id' => 33, 'name' => 'Cilacap', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3302', 'province_id' => 33, 'name' => 'Banyumas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3303', 'province_id' => 33, 'name' => 'Purbalingga', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3304', 'province_id' => 33, 'name' => 'Banjarnegara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3305', 'province_id' => 33, 'name' => 'Kebumen', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3306', 'province_id' => 33, 'name' => 'Purworejo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3307', 'province_id' => 33, 'name' => 'Wonosobo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3309', 'province_id' => 33, 'name' => 'Boyolali', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3310', 'province_id' => 33, 'name' => 'Klaten', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3311', 'province_id' => 33, 'name' => 'Sukoharjo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3312', 'province_id' => 33, 'name' => 'Wonogiri', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3313', 'province_id' => 33, 'name' => 'Karanganyar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3314', 'province_id' => 33, 'name' => 'Sragen', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3315', 'province_id' => 33, 'name' => 'Grobogan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3316', 'province_id' => 33, 'name' => 'Blora', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3317', 'province_id' => 33, 'name' => 'Rembang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3318', 'province_id' => 33, 'name' => 'Pati', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3319', 'province_id' => 33, 'name' => 'Kudus', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3320', 'province_id' => 33, 'name' => 'Jepara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3321', 'province_id' => 33, 'name' => 'Demak', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3323', 'province_id' => 33, 'name' => 'Temanggung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3324', 'province_id' => 33, 'name' => 'Kendal', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3325', 'province_id' => 33, 'name' => 'Batang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3327', 'province_id' => 33, 'name' => 'Pemalang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3329', 'province_id' => 33, 'name' => 'Brebes', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3371', 'province_id' => 33, 'name' => 'Magelang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3372', 'province_id' => 33, 'name' => 'Surakarta', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3373', 'province_id' => 33, 'name' => 'Salatiga', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3374', 'province_id' => 33, 'name' => 'Semarang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3375', 'province_id' => 33, 'name' => 'Pekalongan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3376', 'province_id' => 33, 'name' => 'Tegal', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3401', 'province_id' => 34, 'name' => 'Kulon Progo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3402', 'province_id' => 34, 'name' => 'Bantul', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3403', 'province_id' => 34, 'name' => 'Gunung Kidul', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3404', 'province_id' => 34, 'name' => 'Sleman', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3471', 'province_id' => 34, 'name' => 'Yogyakarta', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3501', 'province_id' => 35, 'name' => 'Pacitan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3502', 'province_id' => 35, 'name' => 'Ponorogo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3503', 'province_id' => 35, 'name' => 'Trenggalek', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3504', 'province_id' => 35, 'name' => 'Tulungagung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3505', 'province_id' => 35, 'name' => 'Blitar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3506', 'province_id' => 35, 'name' => 'Kediri', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3507', 'province_id' => 35, 'name' => 'Malang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3508', 'province_id' => 35, 'name' => 'Lumajang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3509', 'province_id' => 35, 'name' => 'Jember', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3510', 'province_id' => 35, 'name' => 'Banyuwangi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3511', 'province_id' => 35, 'name' => 'Bondowoso', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3512', 'province_id' => 35, 'name' => 'Situbondo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3515', 'province_id' => 35, 'name' => 'Sidoarjo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3517', 'province_id' => 35, 'name' => 'Jombang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3518', 'province_id' => 35, 'name' => 'Nganjuk', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3519', 'province_id' => 35, 'name' => 'Madiun', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3520', 'province_id' => 35, 'name' => 'Magetan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3521', 'province_id' => 35, 'name' => 'Ngawi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3522', 'province_id' => 35, 'name' => 'Bojonegoro', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3523', 'province_id' => 35, 'name' => 'Tuban', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3524', 'province_id' => 35, 'name' => 'Lamongan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3525', 'province_id' => 35, 'name' => 'Gresik', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3526', 'province_id' => 35, 'name' => 'Bangkalan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3527', 'province_id' => 35, 'name' => 'Sampang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3528', 'province_id' => 35, 'name' => 'Pamekasan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3529', 'province_id' => 35, 'name' => 'Sumenep', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3574', 'province_id' => 35, 'name' => 'Probolinggo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3575', 'province_id' => 35, 'name' => 'Pasuruan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3576', 'province_id' => 35, 'name' => 'Mojokerto', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3578', 'province_id' => 35, 'name' => 'Surabaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3579', 'province_id' => 35, 'name' => 'Batu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3601', 'province_id' => 36, 'name' => 'Pandeglang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3602', 'province_id' => 36, 'name' => 'Lebak', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3603', 'province_id' => 36, 'name' => 'Tangerang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3672', 'province_id' => 36, 'name' => 'Cilegon', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3673', 'province_id' => 36, 'name' => 'Serang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3674', 'province_id' => 36, 'name' => 'Tangerang Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5101', 'province_id' => 51, 'name' => 'Jembrana', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5102', 'province_id' => 51, 'name' => 'Tabanan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5103', 'province_id' => 51, 'name' => 'Badung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5104', 'province_id' => 51, 'name' => 'Gianyar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5105', 'province_id' => 51, 'name' => 'Klungkung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5106', 'province_id' => 51, 'name' => 'Bangli', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5107', 'province_id' => 51, 'name' => 'Karang Asem', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5108', 'province_id' => 51, 'name' => 'Buleleng', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5171', 'province_id' => 51, 'name' => 'Denpasar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5201', 'province_id' => 52, 'name' => 'Lombok Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5202', 'province_id' => 52, 'name' => 'Lombok Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5203', 'province_id' => 52, 'name' => 'Lombok Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5204', 'province_id' => 52, 'name' => 'Sumbawa', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5205', 'province_id' => 52, 'name' => 'Dompu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5206', 'province_id' => 52, 'name' => 'Bima', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5207', 'province_id' => 52, 'name' => 'Sumbawa Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5208', 'province_id' => 52, 'name' => 'Lombok Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5271', 'province_id' => 52, 'name' => 'Mataram', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5301', 'province_id' => 53, 'name' => 'Sumba Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5302', 'province_id' => 53, 'name' => 'Sumba Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5303', 'province_id' => 53, 'name' => 'Kupang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5304', 'province_id' => 53, 'name' => 'Timor Tengah Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5305', 'province_id' => 53, 'name' => 'Timor Tengah Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5306', 'province_id' => 53, 'name' => 'Belu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5307', 'province_id' => 53, 'name' => 'Alor', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5308', 'province_id' => 53, 'name' => 'Lembata', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5309', 'province_id' => 53, 'name' => 'Flores Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5310', 'province_id' => 53, 'name' => 'Sikka', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5311', 'province_id' => 53, 'name' => 'Ende', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5312', 'province_id' => 53, 'name' => 'Ngada', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5313', 'province_id' => 53, 'name' => 'Manggarai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5314', 'province_id' => 53, 'name' => 'Rote Ndao', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5315', 'province_id' => 53, 'name' => 'Manggarai Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5316', 'province_id' => 53, 'name' => 'Sumba Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5317', 'province_id' => 53, 'name' => 'Sumba Barat Daya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5318', 'province_id' => 53, 'name' => 'Nagekeo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5319', 'province_id' => 53, 'name' => 'Manggarai Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5320', 'province_id' => 53, 'name' => 'Sabu Raijua', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5321', 'province_id' => 53, 'name' => 'Malaka', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6101', 'province_id' => 61, 'name' => 'Sambas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6102', 'province_id' => 61, 'name' => 'Bengkayang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6103', 'province_id' => 61, 'name' => 'Landak', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6104', 'province_id' => 61, 'name' => 'Mempawah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6105', 'province_id' => 61, 'name' => 'Sanggau', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6106', 'province_id' => 61, 'name' => 'Ketapang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6107', 'province_id' => 61, 'name' => 'Sintang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6108', 'province_id' => 61, 'name' => 'Kapuas Hulu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6109', 'province_id' => 61, 'name' => 'Sekadau', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6110', 'province_id' => 61, 'name' => 'Melawi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6111', 'province_id' => 61, 'name' => 'Kayong Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6112', 'province_id' => 61, 'name' => 'Kubu Raya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6171', 'province_id' => 61, 'name' => 'Pontianak', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6172', 'province_id' => 61, 'name' => 'Singkawang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6201', 'province_id' => 62, 'name' => 'Kotawaringin Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6202', 'province_id' => 62, 'name' => 'Kotawaringin Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6203', 'province_id' => 62, 'name' => 'Kapuas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6204', 'province_id' => 62, 'name' => 'Barito Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6205', 'province_id' => 62, 'name' => 'Barito Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6206', 'province_id' => 62, 'name' => 'Sukamara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6207', 'province_id' => 62, 'name' => 'Lamandau', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6208', 'province_id' => 62, 'name' => 'Seruyan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6209', 'province_id' => 62, 'name' => 'Katingan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6210', 'province_id' => 62, 'name' => 'Pulang Pisau', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6211', 'province_id' => 62, 'name' => 'Gunung Mas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6212', 'province_id' => 62, 'name' => 'Barito Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6213', 'province_id' => 62, 'name' => 'Murung Raya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6271', 'province_id' => 62, 'name' => 'Palangka Raya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6301', 'province_id' => 63, 'name' => 'Tanah Laut', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6302', 'province_id' => 63, 'name' => 'Kota Baru', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6303', 'province_id' => 63, 'name' => 'Banjar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6304', 'province_id' => 63, 'name' => 'Barito Kuala', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6305', 'province_id' => 63, 'name' => 'Tapin', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6306', 'province_id' => 63, 'name' => 'Hulu Sungai Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6307', 'province_id' => 63, 'name' => 'Hulu Sungai Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6308', 'province_id' => 63, 'name' => 'Hulu Sungai Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6309', 'province_id' => 63, 'name' => 'Tabalong', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6310', 'province_id' => 63, 'name' => 'Tanah Bumbu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6311', 'province_id' => 63, 'name' => 'Balangan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6371', 'province_id' => 63, 'name' => 'Banjarmasin', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6372', 'province_id' => 63, 'name' => 'Banjar Baru', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6401', 'province_id' => 64, 'name' => 'Paser', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6402', 'province_id' => 64, 'name' => 'Kutai Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6403', 'province_id' => 64, 'name' => 'Kutai Kartanegara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6404', 'province_id' => 64, 'name' => 'Kutai Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6405', 'province_id' => 64, 'name' => 'Berau', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6409', 'province_id' => 64, 'name' => 'Penajam Paser Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6411', 'province_id' => 64, 'name' => 'Mahakam Hulu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6471', 'province_id' => 64, 'name' => 'Balikpapan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6472', 'province_id' => 64, 'name' => 'Samarinda', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6474', 'province_id' => 64, 'name' => 'Bontang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6501', 'province_id' => 65, 'name' => 'Malinau', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6502', 'province_id' => 65, 'name' => 'Bulungan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6503', 'province_id' => 65, 'name' => 'Tana Tidung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6504', 'province_id' => 65, 'name' => 'Nunukan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6571', 'province_id' => 65, 'name' => 'Tarakan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7101', 'province_id' => 71, 'name' => 'Bolaang Mongondow', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7102', 'province_id' => 71, 'name' => 'Minahasa', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7103', 'province_id' => 71, 'name' => 'Kepulauan Sangihe', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7104', 'province_id' => 71, 'name' => 'Kepulauan Talaud', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7105', 'province_id' => 71, 'name' => 'Minahasa Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7106', 'province_id' => 71, 'name' => 'Minahasa Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7107', 'province_id' => 71, 'name' => 'Bolaang Mongondow Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7108', 'province_id' => 71, 'name' => 'Kepulauan Siau Tagulandang Biaro', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7109', 'province_id' => 71, 'name' => 'Minahasa Tenggara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7110', 'province_id' => 71, 'name' => 'Bolaang Mongondow Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7111', 'province_id' => 71, 'name' => 'Bolaang Mongondow Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7171', 'province_id' => 71, 'name' => 'Manado', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7172', 'province_id' => 71, 'name' => 'Bitung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7173', 'province_id' => 71, 'name' => 'Tomohon', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7174', 'province_id' => 71, 'name' => 'Kotamobagu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7201', 'province_id' => 72, 'name' => 'Banggai Kepulauan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7202', 'province_id' => 72, 'name' => 'Banggai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7203', 'province_id' => 72, 'name' => 'Morowali', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7204', 'province_id' => 72, 'name' => 'Poso', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7205', 'province_id' => 72, 'name' => 'Donggala', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7206', 'province_id' => 72, 'name' => 'Toli-toli', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7207', 'province_id' => 72, 'name' => 'Buol', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7208', 'province_id' => 72, 'name' => 'Parigi Moutong', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7209', 'province_id' => 72, 'name' => 'Tojo Una-una', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7210', 'province_id' => 72, 'name' => 'Sigi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7211', 'province_id' => 72, 'name' => 'Banggai Laut', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7212', 'province_id' => 72, 'name' => 'Morowali Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7271', 'province_id' => 72, 'name' => 'Palu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7301', 'province_id' => 73, 'name' => 'Kepulauan Selayar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7302', 'province_id' => 73, 'name' => 'Bulukumba', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7303', 'province_id' => 73, 'name' => 'Bantaeng', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7304', 'province_id' => 73, 'name' => 'Jeneponto', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7305', 'province_id' => 73, 'name' => 'Takalar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7306', 'province_id' => 73, 'name' => 'Gowa', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7307', 'province_id' => 73, 'name' => 'Sinjai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7308', 'province_id' => 73, 'name' => 'Maros', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7309', 'province_id' => 73, 'name' => 'Pangkajene Dan Kepulauan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7310', 'province_id' => 73, 'name' => 'Barru', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7311', 'province_id' => 73, 'name' => 'Bone', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7312', 'province_id' => 73, 'name' => 'Soppeng', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7313', 'province_id' => 73, 'name' => 'Wajo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7314', 'province_id' => 73, 'name' => 'Sidenreng Rappang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7315', 'province_id' => 73, 'name' => 'Pinrang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7316', 'province_id' => 73, 'name' => 'Enrekang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7317', 'province_id' => 73, 'name' => 'Luwu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7318', 'province_id' => 73, 'name' => 'Tana Toraja', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7322', 'province_id' => 73, 'name' => 'Luwu Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7325', 'province_id' => 73, 'name' => 'Luwu Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7326', 'province_id' => 73, 'name' => 'Toraja Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7371', 'province_id' => 73, 'name' => 'Makassar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7372', 'province_id' => 73, 'name' => 'Parepare', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7373', 'province_id' => 73, 'name' => 'Palopo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7401', 'province_id' => 74, 'name' => 'Buton', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7402', 'province_id' => 74, 'name' => 'Muna', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7403', 'province_id' => 74, 'name' => 'Konawe', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7404', 'province_id' => 74, 'name' => 'Kolaka', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7405', 'province_id' => 74, 'name' => 'Konawe Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7406', 'province_id' => 74, 'name' => 'Bombana', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7407', 'province_id' => 74, 'name' => 'Wakatobi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7408', 'province_id' => 74, 'name' => 'Kolaka Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7409', 'province_id' => 74, 'name' => 'Buton Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7410', 'province_id' => 74, 'name' => 'Konawe Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7411', 'province_id' => 74, 'name' => 'Kolaka Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7412', 'province_id' => 74, 'name' => 'Konawe Kepulauan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7413', 'province_id' => 74, 'name' => 'Muna Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7414', 'province_id' => 74, 'name' => 'Buton Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7415', 'province_id' => 74, 'name' => 'Buton Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7471', 'province_id' => 74, 'name' => 'Kendari', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7472', 'province_id' => 74, 'name' => 'Baubau', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7501', 'province_id' => 75, 'name' => 'Boalemo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7503', 'province_id' => 75, 'name' => 'Pohuwato', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7504', 'province_id' => 75, 'name' => 'Bone Bolango', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7505', 'province_id' => 75, 'name' => 'Gorontalo Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7571', 'province_id' => 75, 'name' => 'Gorontalo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7601', 'province_id' => 76, 'name' => 'Majene', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7602', 'province_id' => 76, 'name' => 'Polewali Mandar', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7603', 'province_id' => 76, 'name' => 'Mamasa', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7604', 'province_id' => 76, 'name' => 'Mamuju', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7605', 'province_id' => 76, 'name' => 'Mamuju Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7606', 'province_id' => 76, 'name' => 'Mamuju Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8101', 'province_id' => 81, 'name' => 'Maluku Tenggara Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8102', 'province_id' => 81, 'name' => 'Maluku Tenggara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8103', 'province_id' => 81, 'name' => 'Maluku Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8104', 'province_id' => 81, 'name' => 'Buru', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8105', 'province_id' => 81, 'name' => 'Kepulauan Aru', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8106', 'province_id' => 81, 'name' => 'Seram Bagian Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8107', 'province_id' => 81, 'name' => 'Seram Bagian Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8108', 'province_id' => 81, 'name' => 'Maluku Barat Daya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8109', 'province_id' => 81, 'name' => 'Buru Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8171', 'province_id' => 81, 'name' => 'Ambon', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8172', 'province_id' => 81, 'name' => 'Tual', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8201', 'province_id' => 82, 'name' => 'Halmahera Barat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8202', 'province_id' => 82, 'name' => 'Halmahera Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8203', 'province_id' => 82, 'name' => 'Kepulauan Sula', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8204', 'province_id' => 82, 'name' => 'Halmahera Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8205', 'province_id' => 82, 'name' => 'Halmahera Utara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8206', 'province_id' => 82, 'name' => 'Halmahera Timur', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8207', 'province_id' => 82, 'name' => 'Pulau Morotai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8208', 'province_id' => 82, 'name' => 'Pulau Taliabu', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8271', 'province_id' => 82, 'name' => 'Ternate', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8272', 'province_id' => 82, 'name' => 'Tidore Kepulauan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9101', 'province_id' => 91, 'name' => 'Fakfak', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9102', 'province_id' => 91, 'name' => 'Kaimana', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9103', 'province_id' => 91, 'name' => 'Teluk Wondama', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9104', 'province_id' => 91, 'name' => 'Teluk Bintuni', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9105', 'province_id' => 91, 'name' => 'Manokwari', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9106', 'province_id' => 91, 'name' => 'Sorong Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9108', 'province_id' => 91, 'name' => 'Raja Ampat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9109', 'province_id' => 91, 'name' => 'Tambrauw', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9110', 'province_id' => 91, 'name' => 'Maybrat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9111', 'province_id' => 91, 'name' => 'Manokwari Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9112', 'province_id' => 91, 'name' => 'Pegunungan Arfak', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9171', 'province_id' => 91, 'name' => 'Sorong', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9401', 'province_id' => 94, 'name' => 'Merauke', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9402', 'province_id' => 94, 'name' => 'Jayawijaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9403', 'province_id' => 94, 'name' => 'Jayapura', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9404', 'province_id' => 94, 'name' => 'Nabire', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9408', 'province_id' => 94, 'name' => 'Kepulauan Yapen', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9409', 'province_id' => 94, 'name' => 'Biak Numfor', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9410', 'province_id' => 94, 'name' => 'Paniai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9411', 'province_id' => 94, 'name' => 'Puncak Jaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9412', 'province_id' => 94, 'name' => 'Mimika', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9413', 'province_id' => 94, 'name' => 'Boven Digoel', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9414', 'province_id' => 94, 'name' => 'Mappi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9415', 'province_id' => 94, 'name' => 'Asmat', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9416', 'province_id' => 94, 'name' => 'Yahukimo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9417', 'province_id' => 94, 'name' => 'Pegunungan Bintang', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9418', 'province_id' => 94, 'name' => 'Tolikara', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9419', 'province_id' => 94, 'name' => 'Sarmi', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9420', 'province_id' => 94, 'name' => 'Keerom', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9426', 'province_id' => 94, 'name' => 'Waropen', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9427', 'province_id' => 94, 'name' => 'Supiori', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9428', 'province_id' => 94, 'name' => 'Mamberamo Raya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9429', 'province_id' => 94, 'name' => 'Nduga', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9430', 'province_id' => 94, 'name' => 'Lanny Jaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9431', 'province_id' => 94, 'name' => 'Mamberamo Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9432', 'province_id' => 94, 'name' => 'Yalimo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9433', 'province_id' => 94, 'name' => 'Puncak', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9434', 'province_id' => 94, 'name' => 'Dogiyai', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9435', 'province_id' => 94, 'name' => 'Intan Jaya', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9436', 'province_id' => 94, 'name' => 'Deiyai', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
